config/routes.rb
Rails.application.routes.draw do
  resources :pictures do
    collection do
      post :confirm
    end
    resources :comments
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :content, presence: true
  validates :image, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_picture, only: [:create, :edit, :update]
  def create
    @comment = @picture.comments.build(comment_params)

    respond_to do |f|
      if @comment.save
        # f.html { redirect_to picture_path(@picture) }
        f.js { render :index }
      else
        f.html { redirect_to picture_path(@picture), notice: '投稿できませんでした' }
      end
    end
  end

  def edit
    @comment = @picture.comments.find(params[:id])
    respond_to do |f|
      flash.now[:notice] = 'コメントの編集中'
      f.js { render :edit }
    end
  end

  def update
    @comment = @picture.comments.find(params[:id])
    respond_to do |f|
      if @comment.update(comment_params)
        flash.now[:notice] = 'コメントが編集されました'
        f.js { render :index }
      else
        flash.now[:notice] = 'コメントが編集されました'
        f.js { render :edit_error }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |f|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:picuture_id, :content)
  end
  def set_picture
    @picture = Picture.find(params[:picture_id])
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        redirect_to pictures_path, notice: '投稿しました'
      else
        render :new
      end
    end
  end

  def show
    @comments = @picture.comments
    @comment = @picture.comments.build
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: '削除しました'
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  private
  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user= User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_edit.html.erb
<%= form_with(model: [@picture, @comment]) do |f| %>
  <% if @comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= puralize(@comment.errors.count, "errors") %> prohibited this comment from being saved:</h2>
    <ul>
      <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, id: "comment_content_#{picture.id}"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [@picture, @comment]) do |f| %>
  <% if @comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= puralize(@comment.errors.count, "errors") %> prohibited this comment from being saved:</h2>
    <ul>
      <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <li>
        <div class="comment-content" id="this_comment_<%= @comment.id %>"></div>
        <p><%= comment.content%></p>
        <p><%= link_to 'コメント編集', edit_picture_comment_path(@picture, comment),remote: true %></p>
        <p><%= link_to 'コメント削除', picture_comment_path(comment.picture_id, comment.id), method: :delete, remote: true,
                                      data: { confirm: '本当に削除しますか？' } %></p>

      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', picture: @picture, comment: @comment %>")

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.picture.comments, picture: @comment.picture  }) %>")
$("text_area").val('')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageFace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<div class="navbar">
  <h2 class="logo">ImageFace</h2>
    <% if logged_in? %>
      <ul>
        <li><%= link_to "Profile", user_path(current_user.id) %></li>
        <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
    <% else %>
        <li><%= link_to "Sign up", new_user_path %></li>
          <li><%= link_to "Login", new_session_path %></li>
      </ul>
    <% end %>
</div>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<div class="user_page">
  <%= form_with(model: @picture, local: true,url: choose_new_or_edit) do |form| %>
    <ul class="field">
      <li><%= form.label :image %></li>
      <li><%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></li>
      <li><%= form.file_field :image %></li>
      <li><%= form.hidden_field :image_cache %></li>
    </ul>
  <div class="content">
     <%= form.label :content %>
     <%= form.text_field :content %>
   </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @picture, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>本文:<%= @picture.content %></p>
  <%= form.hidden_field :image_cache %>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <div class="sub_buttun">
    <%= form.submit  "登録する" %>
    <%= form.submit "戻る", name: 'back' %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h2>編集する</h2>
<%= render 'form' %>

app/views/pictures/index.html.erb
<h1>一覧</h1>
<% @pictures.each do |picture| %>
<ul>
  <li><%= picture.user.name %></li>
  <li><%= image_tag picture.image.url %></li>
  <div class="content_box">
    <%= picture.content %>
  </div>
</ul>
<div class="edit_tag">
  <div class="simple_button">
    <%= link_to '詳細を確認する', picture_path(picture.id) %>
  </div>
  <div class="simple_button">
    <%= link_to "編集する", edit_picture_path(picture.id), data: { confirm: '本当に編集していいですか？' } %>
  </div>
  <div class="simple_button">
    <%= link_to "削除する", picture_path(picture.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %>
  </div>
</div>
<% end %>

app/views/pictures/new.html.erb
<h2>投稿を作成</h2>
<%= render 'form' %>
<div class="simple_button">
  <%= link_to "投稿一覧へ", pictures_path %>
</div>

app/views/pictures/show.html.erb
<h2><%= @picture.user.name %>さんの詳細画面</h2>
<div class="user_page">
  <p>image:<br><%= image_tag @picture.image.url %></p>
  <p>内容: <%= @picture.content %></p>
</div>
<p>コメント一覧</p>
<div id="comments_area">
  <%= render partial: 'comments/index', locals: { comments: @comments, blog: @blog } %>
</div>
<%= render partial: 'comments/form', locals: { comments: @comments, blog: @blog } %>
<%= link_to '編集', edit_picture_path(@picture) %>
<%= link_to '戻る', pictures_path %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
<div class="sign_up_page">
  <ul>
    <h1>Sign up</h1>
    <li>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
    <li>
      <%= f.label :email %>
      <%= f.email_field :email %>
    </li>
    <li>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </li>
    <li>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </li>
  </ul>
</div>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<div class="user_detail">
    <h3><%= @user.name %>のページ</h3><br>
    <h3>メールアドレス: <%= @user.email %></h3>
</div>
  <div class="simple_button">
    <%= link_to '新規投稿へ', new_picture_path %>
  </div>